### ISSUE TITLE
refactor: Restructure and refactor codebase entirely

### ISSUE THREAD

**Issue by mcao** [tyffical/Pridebot#60]
**Is your feature request related to a problem? Please describe.**
The Pridebot codebase needs to be refactored entirely to be in line with standard programming conventions and etiquette. 

**Describe the ideal solution**
I will submit a pull request shortly which will address this issue and refactor the codebase,

**Describe alternatives you've considered**
Annoying @tyffical until she refactors it herself

**Additional context**
What do I put here

**Comment by tyffical** [comment]
lolll i would refactor it myself if i was free. Which is never
